/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EnergyLogStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEnergyLog"
      | "getDate"
      | "getElectricity"
      | "getGas"
      | "getLog"
      | "getLogCount"
      | "getWater"
      | "protocolId"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addEnergyLog",
    values: [string, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getElectricity",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getGas",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLog",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLogCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWater",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addEnergyLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getElectricity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getGas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLogCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWater", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export interface EnergyLogStorage extends BaseContract {
  connect(runner?: ContractRunner | null): EnergyLogStorage;
  waitForDeployment(): Promise<this>;

  interface: EnergyLogStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEnergyLog: TypedContractMethod<
    [
      date: string,
      electricity: BytesLike,
      gas: BytesLike,
      water: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getDate: TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;

  getElectricity: TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;

  getGas: TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;

  getLog: TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [
      [string, string, string, string] & {
        date: string;
        electricity: string;
        gas: string;
        water: string;
      }
    ],
    "view"
  >;

  getLogCount: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  getWater: TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEnergyLog"
  ): TypedContractMethod<
    [
      date: string,
      electricity: BytesLike,
      gas: BytesLike,
      water: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDate"
  ): TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getElectricity"
  ): TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGas"
  ): TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLog"
  ): TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [
      [string, string, string, string] & {
        date: string;
        electricity: string;
        gas: string;
        water: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLogCount"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWater"
  ): TypedContractMethod<
    [account: AddressLike, index: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
